name: Icon request
description: Request a specific icon
labels: [icon request]
assignees:
  - miguelsolorio
body:
  - type: checkboxes
    attributes:
      label: Type
      description: What type of icon would you like added?
      options:
        - label: File icon
        - label: Folder icon
  - type: textarea
    attributes:
      label: Context and associations
      description: What language/extension/file/folder name(s) should the icon be associated with?
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: Links, images, docs with ideas/examples of what the icon should look like. Please reference the Symbols Figma file (https://www.figma.com/file/HYLMyRbIdSbIJQlqnd9pSN/Symbols---File-Icons) for style guidelines. Try to limit colors to existing icon colors (tailwind palette).
    validations:
      required: true
