name: Association request
description: Request an existing icon to have new association(s)
labels: [association request]
assignees:
  - miguelsolorio
body:
  - type: input
    attributes:
      label: Icon
      description: What icon do you want new associations for? You can preview available icons at https://github.com/miguelsolorio/vscode-symbols/blob/main/preview/preview.md
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context and associations
      description: What language/extension/file/folder name(s) should the icon be associated with?
    validations:
      required: true
