name: CI

on:
  push:
    branches: [main]
    tags-ignore: [v*]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Lint with Biome
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run check-format

      - name: Check icon integrity
        run: pnpm run integrity
